// import "@coolui/theme/styles.css";
import { ThemeProvider } from "@coolui/theme/client";
import "./globals.css";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { getThemeScript } from "@coolui/theme";
import { Layout, LayoutProvider } from "@coolui/layout/client";
// import {  ThemeProvider } from "@coolui/theme/client";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <script dangerouslySetInnerHTML={{ __html: getThemeScript() }}></script>
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} `}
      >
        <ThemeProvider>
          <LayoutProvider>
            <Layout
              menu={<div> menu here</div>}
              footer={<p>© {new Date().getFullYear()} uicool. All rights reserved.</p>}
              logo={{
                wordmark: "CoolUI",
              }}
            >
              {children}
            </Layout>
          </LayoutProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
