import "./globals.css";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import { getThemeScript } from "@coolui/theme";
import { ThemeProvider } from "@coolui/theme/client";

import { AppLayout, AppStateProvider } from "@coolui/application/client";
import { createAppConfig, defaultAppConfig } from "@coolui/application";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const appConfig = createAppConfig(defaultAppConfig)

export default function NextRootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <script dangerouslySetInnerHTML={{ __html: getThemeScript() }}></script>
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} `}
      >
        <ThemeProvider>
          <AppStateProvider>
            <AppLayout
              appConfig={appConfig}
              // content={{
              //   headerActions: undefined,
              //   headerToolbar: undefined,
              //   sidebarHeader: undefined,
              //   sidebarBody: undefined,
              //   sidebarFooter: undefined,
              // }}
            >
              {children}
            </AppLayout>
          </AppStateProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
