
import "./globals.css";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import { AppLayout, AppLayoutProvider, ThemeProvider } from "@coolui/application/client";
import { NextThemeScript } from "@coolui/application";
import { LAYOUT_CONFIG, THEME_CONFIG } from "./config";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};




export default function NextRootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <NextThemeScript config={THEME_CONFIG}/>
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} `}
      >
        <ThemeProvider config={THEME_CONFIG}>
          <AppLayoutProvider>
            <AppLayout {...LAYOUT_CONFIG}>
              {children}
            </AppLayout>
          </AppLayoutProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
